### ISSUE TITLE
[SOLVED] Firefox fails to show display

### ISSUE THREAD

**Issue by Manfred-Knick** [djpohly/dwl#262] opened 2022-06-27 09:32 UTC
## Info
dwl's commit: 72e0a560d9836c5e8658003f548203bcd722e565 (today's latest, just 2 days ago)
wlroots version: 0.15.1

Running on Gentoo + GURU Overlay, I *very* much enjoy 
o   gui-wm/dwl
o   dev-libs/bemenu
o   x11-terms/alacritty
o   gui-apps/somebar

o   dwl USE flag "X" ("Add support for X11") is *set*.
o   gui-libs/wlroots :  USE flag "x11-backend" is not necessarily needed for Firefox

o   WLR_NO_HARDWARE_CURSORS=1
o   MOZ_ENABLE_WAYLAND=1

<<< DELETED >>>

rules[] in former dwm config.h:
o   { "firefox",  NULL,       1 << **5**,       0,           -1 },

rules[] in new dwl config.h:
o   { "firefox",  NULL,       1 << **8**,       0,           -1 },

Starting from console an Tab 1,
on WQHD monitors, the resulting dot is sooo tiny ... could have been a pixel error !
I did not recognize it at all.

SUGGESTION: make it a little bit bigger ... or three dots, maybe?

**Comment by fauxmight** [comment] 2022-06-27 16:08
@Manfred-Knick Are you referring to a dot in the somebar tag indicator?
If so, this is not a dwl issue.
If not, the issue is unclear.

**Comment by Manfred-Knick** [comment] 2022-06-27 17:20
Please, feel free to close.

**Comment by fauxmight** [comment] 2022-06-27 17:33
Thank you for making that clear.
You have the capability of closing an issue you've opened.
(I am a mere contributor here and cannot close an issue I did not open.)

**Closed** 2022-06-28 01:06 UTC
Labels: A: bug
