### ISSUE TITLE
Fail to start cleanly with XWAYLAND enabled

### ISSUE THREAD

**Issue by Eluminae** [djpohly/dwl#98] opened 2021-03-12 10:11 UTC
Hello there !

I read some other issues that could be related. Sorry if this is duplicate

Starting dwl when compiled with XWAYLAND seems partially broken. Init script is not run and xwayland seems disabled as X11 dependand windows do not display themselves but no errors seems logged in stderr.

The only logs I got are :

```
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
Errors from xkbcomp are not fatal to the X server
XKB: Failed to compile keymap
Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
(EE)
Fatal server error:
(EE) Failed to activate virtual core keyboard: 2(EE)
```

But another issues seems to say that this is not related, or not important.

I dont have time to look at the code at this time so I just report my issue here. I'll take a look later

**Comment by djpohly** [comment] 2021-03-13 16:35
Duplicate of #97.

**Closed by djpohly** 2021-03-13 16:35 UTC
