### ISSUE TITLE
inhibit_idle for fullscreen windows

### ISSUE THREAD

**Issue by korei999** [djpohly/dwl#407] opened 2023-04-05 18:48 UTC
Is there a way to do something like `for_window [class="^.*"] inhibit_idle fullscreen` as sway or hyrpland does with swayidle. My monitor turns off if I, for example, watch fullscreen youtube video, or play game with controller.

**Comment by sevz17** [comment] 2023-04-23 01:59
> Is there a way to do something like `for_window [class="^.*"] inhibit_idle fullscreen` as sway or hyrpland does with swayidle.

Currently is not possible, for that you'd need to write a patch. Put something like this after the loop in `checkidleinhibit()`:

```c
int inhibit = 0;
Client *c;
wl_list_foreach(c, &clients, link) {
	if (c->isfullscreen && VISIBLEON(c, c->mon)) {
		inhibit = 1;
		break;
	}
}
```

NOTE: I just created it, and I don't even now if it compiles fine.

> My monitor turns off if I, for example, watch fullscreen youtube video.

That's weird, your browser should inhibit idle when playing a video.

**Comment by korei999** [comment] 2023-04-23 21:43
I tried this, but i see no change.
```c
void
checkidleinhibitor(struct wlr_surface *exclude)
{
	Client *c;
	int inhibited = 0, unused_lx, unused_ly;

	struct wlr_idle_inhibitor_v1 *inhibitor;
	wl_list_for_each(inhibitor, &idle_inhibit_mgr->inhibitors, link) {
		struct wlr_surface *surface = wlr_surface_get_root_surface(inhibitor->surface);
		struct wlr_scene_tree *tree = surface->data;
		if (exclude != surface && (bypass_surface_visibility || (!tree
				|| wlr_scene_node_coords(&tree->node, &unused_lx, &unused_ly)))) {
			inhibited = 1;
			break;
		}
	}

	wl_list_for_each(c, &clients, link) {
		if (c->isfullscreen && VISIBLEON(c, c->mon)) {
			inhibited = 1;
			break;
		}
	}

	wlr_idle_set_enabled(idle, NULL, !inhibited);
	wlr_idle_notifier_v1_set_inhibited(idle_notifier, inhibited);
}
```

> That's weird, your browser should inhibit idle when playing a video.

Yeah you're right, its actually fine with mpv and firefox, but (apparently) wierd with chromium.

**Comment by sevz17** [comment] 2023-06-02 01:38
Mmm, what about this diff?, only disables idle tracking if the current client is fullscreen though.

```diff
diff --git a/dwl.c b/dwl.c
index aec7427..f6b6a27 100644
--- a/dwl.c
+++ b/dwl.c
@@ -633,6 +633,7 @@ checkidleinhibitor(struct wlr_surface *exclude)
 {
 	int inhibited = 0, unused_lx, unused_ly;
 	struct wlr_idle_inhibitor_v1 *inhibitor;
+	Client *c;
 	wl_list_for_each(inhibitor, &idle_inhibit_mgr->inhibitors, link) {
 		struct wlr_surface *surface = wlr_surface_get_root_surface(inhibitor->surface);
 		struct wlr_scene_tree *tree = surface->data;
@@ -643,6 +644,10 @@ checkidleinhibitor(struct wlr_surface *exclude)
 		}
 	}
 
+	c = focustop(selmon);
+	if (c && c->isfullscreen)
+		inhibited = 1;
+
 	wlr_idle_set_enabled(idle, NULL, !inhibited);
 	wlr_idle_notifier_v1_set_inhibited(idle_notifier, inhibited);
 }
```

**Comment by sevz17** [comment] 2023-06-02 01:41
Oh, btw, since the problem is chromium and I don't intent to merge this to mainline I'll close the issue.

**Closed by sevz17** 2023-06-02 01:41 UTC
