### ISSUE TITLE
.options model layout is not working for me the keyboard is "us" and not "it"

### ISSUE THREAD

**Issue by enrico20026** [djpohly/dwl#14] opened 2020-07-02 09:15 UTC
is this correct?
``` c
static const struct xkb_rule_names xkb_rules = {
	/* can specify fields: rules, model, layout, variant, options */
	/* example:
	.options = "ctrl:nocaps",
	*/
	.model = "pc105",
	.layout = "it",
	.options = "grp:win_space_toggle",
};
```
I dont know how to get italian keyboard-
thanks!

**Comment by theotherjimmy** [comment] 2020-07-02 15:44
Popin' by for a github formatting tip: use ` ``` C` on the line before code blocks and ` ``` ` after it to preserve indentation and get syntax highlighting. for example:
``` C
static const struct xkb_rule_names xkb_rules = {
    /* can specify fields: rules, model, layout, variant, options /
    / example:
    .options = "ctrl:nocaps",
    */
    .model = "pc105",
    .layout = "it",
    .options = "grp:win_space_toggle",
};
```

**Comment by djpohly** [comment] 2020-07-02 20:51
Hm, I tried the same settings (running dwl under X) and got the "òàù" just fine.  I'll try running it directly on a separate VT once I figure out why my VTs aren't currently working (?!).

Apologies if this is a silly question, but did you make sure to re-compile after changing config.h?

**Comment by djpohly** [comment] 2020-07-05 15:46
Update - tested on a VT and it still works for me.  I get the Italian keyboard when I change the settings posted above.  @enrico20026, is this still not working?  If it is not, can you post your full config.h to help us test?

**Comment by djpohly** [comment] 2020-07-21 22:38
Closing since I can't reproduce the issue, but feel free to reopen if it still isn't working and you have some more information - thanks!

**Closed by djpohly** 2020-07-21 22:38 UTC
