### ISSUE TITLE
waitpid for Xwayland fork failed: No child processes

### ISSUE THREAD

**Issue by jbeich** [djpohly/dwl#177] opened 2021-12-31 14:17 UTC
After building with `-DXWAYLAND` starting X11 apps still fails. Xwayland in other compositors works fine: sway, hikari, wayfire, cage, river, labwc, kwin_wayland, mutter, arcan-wayland.

```
$ dwl &
$ glxgears
Error: couldn't open display :0
[...]
00:00:11.336 [xwayland/server.c:92] Starting Xwayland on :0
00:00:11.448 [types/wlr_surface.c:741] New wlr_surface 0x820961a00 (res 0x82094df80)
00:00:11.451 [xwayland/server.c:243] waitpid for Xwayland fork failed: No child processes
(EE) failed to read Wayland events: Broken pipe
```

```
$ cc --version
FreeBSD clang version 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin

$ pkg info -x dwl wayland wlroots
dwl-0.2.2
wayland-1.20.0
wayland-protocols-1.24
xwayland-devel-21.0.99.1.156
wlroots-0.15.0_1
```

**Comment by KNIX3** [comment] 2022-03-24 01:10
Any update on this? I'm having the same issue on even on Linux rather than FreeBSD.

**Comment by Sevz17** [comment] 2022-03-28 23:13
The problem is caused because we setup a SIGCHLD handler.

I think we can fix it with a double fork in `spawn()`

**Comment by djpohly** [comment] 2022-03-29 21:24
Could you check to see if the recently merged #212 fixes the issue?

**Comment by jbeich** [comment] 2022-03-29 21:58
Note, merging in non-default branch is why this issue wasn't automatically closed.

**Comment by jbeich** [comment] 2022-04-09 17:43
Do you plan to merge e08bd1292288 into `main` branch? I'd like to avoid having to rebase it [downstream](https://github.com/freebsd/freebsd-ports/commit/d0ada09b16b1):
```
$ git checkout v0.3 && git cherry-pick -x e08bd1292288
Auto-merging dwl.c
[detached HEAD c7b5bb7] make sure to leave XWayland process waitable
 Author: Devin J. Pohly <djpohly@gmail.com>
 Date: Tue Mar 29 15:55:06 2022 -0500
 1 file changed, 7 insertions(+), 2 deletions(-)


$ git checkout main && git cherry-pick -x e08bd1292288
Auto-merging dwl.c
CONFLICT (content): Merge conflict in dwl.c
error: could not apply e08bd12... make sure to leave XWayland process waitable
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
```

**Closed** 2022-12-02 16:09 UTC
Labels: A: bug
